### PR TITLE
fix: support for GHC 9.10 api

### LINKED ISSUE #137: Compilation failure with GHC 9.10.1-alpha3: ‘HsAppType’ should have 3 arguments, but has been given 4
Here is the result of compiling PyF with GHC 9.10.1-alpha3

```
src/PyF/Internal/Meta.hs:165:10: error: [GHC-27346]
    • The data constructor ‘HsAppType’ should have 3 arguments, but has been given 4
    • In the pattern: HsAppType _ e _ HsWC {hswc_body}
      In an equation for ‘toExp’:
          toExp d (HsAppType _ e _ HsWC {hswc_body})
            = TH.AppTypeE (toExp d . unLoc $ e) (toType . unLoc $ hswc_body)
    |
165 | toExp d (Expr.HsAppType _ e _ HsWC{hswc_body}) = TH.AppTypeE (toExp d . unLoc $ e) (toType . unLoc $ hswc_body)
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by guibou**
Close #137.

### CODE REVIEW

**Comment by tchoutri** [comment]
I'm getting:

```
[5 of 8] Compiling PyF.Internal.Meta ( src/PyF/Internal/Meta.hs, dist/build/PyF/Internal/Meta.o, dist/build/PyF/Internal/Meta.dyn_o )

src/PyF/Internal/Meta.hs:143:25: error: [GHC-76037]
    Not in scope: type constructor or class ‘Pat.ArgPat’
    NB: the module ‘GHC.Hs.Pat’ does not export ‘ArgPat’.
    Suggested fix:
      Perhaps use one of these:
        ‘Pat.Pat’ (imported from GHC.Hs.Pat),
        ‘Pat.LPat’ (imported from GHC.Hs.Pat)
    |
143 | toArgPat :: DynFlags -> Pat.ArgPat GhcPs -> TH.ArgPat
    |                         ^^^^^^^^^^

src/PyF/Internal/Meta.hs:143:45: error: [GHC-76037]
    Not in scope: type constructor or class ‘TH.ArgPat’
    NB: the module ‘Language.Haskell.TH.Syntax’ does not export ‘ArgPat’.
    |
143 | toArgPat :: DynFlags -> Pat.ArgPat GhcPs -> TH.ArgPat
    |                                             ^^^^^^^^^

src/PyF/Internal/Meta.hs:144:20: error: [GHC-76037]
    Not in scope: data constructor ‘Pat.VisPat’
    NB: the module ‘GHC.Hs.Pat’ does not export ‘VisPat’.
    Suggested fix:
      Perhaps use one of these:
        ‘Pat.AsPat’ (imported from GHC.Hs.Pat),
        ‘Pat.LitPat’ (imported from GHC.Hs.Pat),
        ‘Pat.SigPat’ (imported from GHC.Hs.Pat)
    |
144 | toArgPat dynFlags (Pat.VisPat _ pat) = TH.VisAP $ toPat dynFlags $ unLoc pat
    |                    ^^^^^^^^^^

src/PyF/Internal/Meta.hs:144:40: error: [GHC-76037]
    Not in scope: data constructor ‘TH.VisAP’
    NB: the module ‘Language.Haskell.TH.Syntax’ does not export ‘VisAP’.
    Suggested fix:
      Perhaps use one of these:
        ‘TH.ListP’ (imported from Language.Haskell.TH.Syntax),
        ‘TH.ViewP’ (imported from Language.Haskell.TH.Syntax)
    |
144 | toArgPat dynFlags (Pat.VisPat _ pat) = TH.VisAP $ toPat dynFlags $ unLoc pat
    |                                        ^^^^^^^^
```

**Comment by tchoutri** [comment]
You can test GHC 9.10 alpha with GHCup:

```bash
$ ghcup config add-release-channel https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-prereleases-0.0.8.yaml
$ ghcup install ghc 9.10.0.20240413
```

**Comment by guibou** [comment]
@tchoutri sorry, you may retest now. (Tested with GHC 9.10-alpha3 here)

**Comment by tchoutri** [comment]
@guibou Perfect, it compiles! Thank you!

**Pull request merged**
