### PR TITLE
Test broader GHC versions

### LINKED ISSUE #94: Incorrect version bounds
PyF 0.8.1.0 is the last version to work with base <4.11 (GHC <8.4), but the cabal bounds haven't been updated.

This problem also affects revisions 0.8.1.1 and 0.8.1.2, I just point it out because they're not major version bumps from the last one that worked.

Pinning a dependency to `==0.8.1.0` won't work on GHC 8.8+, since it requires `template-haskell <2.15`.

### PR DESCRIPTION
**Pull request by sellout**
This also adds explicit version bounds.

Fixes #94.

### CODE REVIEW

**Comment by guibou** [comment]
I'm surprised, I was sure that I was testing and using PyF with GHC 9.2, but looks like I may have dreamed about it only, and then you did it.

Thank you. I'll press merge once the test are succesful.

**Comment by sellout** [comment]
9.2 is there for nix_build in main, but it's failing. So my initial change removed it. Then the later one fixes the issue and adds it back both for nix_build and slack_build.

**Comment by jkachmar** [comment]
Looks like tests are passing, is this good to be merged?

**Comment by guibou** [comment]
Thank you, sorry for the latency in my answer.

**Pull request merged**
